var {fee_object,nationality_type_object,courses_object, levels_object, amount}=require("./constants");
var structure_of_fee={
    [fee_object['Exam Fee']]:{
       [nationality_type_object['INDIAN']]:{
          [courses_object['Ayurveda']]:{
             [levels_object["UG"]]:{
               [amount]:400
             },
             [levels_object["PG"]]:{
                [amount]:400
             },
             [levels_object["DIPLOMA"]]:{
                [amount]:400
             },
             [levels_object["Ph.D"]]:{
                [amount]:400
             }
          },
          [courses_object['Dental']]:{
            [levels_object["UG"]]:{
                [amount]:400
            },
            [levels_object["PG"]]:{
                [amount]:400
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:400
            },
            [levels_object["Ph.D"]]:{
                [amount]:400
            }
          },
          [courses_object['Medical']]:{
            [levels_object["UG"]]:{
                [amount]:400
            },
            [levels_object["PG"]]:{
                [amount]:400
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:400
            },
            [levels_object["Ph.D"]]:{
                [amount]:400
            }
          }
       },
       [nationality_type_object['FOREIGN']]:{
        [courses_object['Ayurveda']]:{
            [levels_object["UG"]]:{
                [amount]:100
            },
            [levels_object["PG"]]:{
                [amount]:100
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:100
            },
            [levels_object["Ph.D"]]:{
                [amount]:100
            }
        },
        [courses_object['Dental']]:{
            [levels_object["UG"]]:{
                [amount]:100
            },
            [levels_object["PG"]]:{
                [amount]:100
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:100
            },
            [levels_object["Ph.D"]]:{
                [amount]:100
            }
        },
        [courses_object['Medical']]:{
            [levels_object["UG"]]:{
                [amount]:100
            },
            [levels_object["PG"]]:{
                [amount]:100
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:100
            },
            [levels_object["Ph.D"]]:{
                [amount]:100
            }
        }
       },
       [nationality_type_object['NRI']]:{
        [courses_object['Ayurveda']]:{
            [levels_object["UG"]]:{
                [amount]:600
            },
            [levels_object["PG"]]:{
                [amount]:600
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:600
            },
            [levels_object["Ph.D"]]:{
                [amount]:600
            }
        },
        [courses_object['Dental']]:{
            [levels_object["UG"]]:{
                [amount]:600
            },
            [levels_object["PG"]]:{
                [amount]:600
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:600
            },
            [levels_object["Ph.D"]]:{
                [amount]:600
            }
        },
        [courses_object['Medical']]:{
            [levels_object["UG"]]:{
                [amount]:600
            },
            [levels_object["PG"]]:{
                [amount]:600
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:600
            },
            [levels_object["Ph.D"]]:{
                [amount]:600
            }
        }
       },
       [nationality_type_object['SAARC']]:{
        [courses_object['Ayurveda']]:{
            [levels_object["UG"]]:{
                [amount]:600
            },
            [levels_object["PG"]]:{
                [amount]:600
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:600
            },
            [levels_object["Ph.D"]]:{
                [amount]:600
            }
        },
        [courses_object['Dental']]:{
            [levels_object["UG"]]:{
                [amount]:600
            },
            [levels_object["PG"]]:{
                [amount]:600
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:600
            },
            [levels_object["Ph.D"]]:{
                [amount]:600
            }
        },
        [courses_object['Medical']]:{
            [levels_object["UG"]]:{
                [amount]:600
            },
            [levels_object["PG"]]:{
                [amount]:600
            },
            [levels_object["DIPLOMA"]]:{
                [amount]:600
            },
            [levels_object["Ph.D"]]:{
                [amount]:600
            }
        }
       }
    },
    [fee_object['Application Fee']]:{
        [nationality_type_object['INDIAN']]:{
            [courses_object['Ayurveda']]:{
                [levels_object["UG"]]:{
                    [amount]:200
                },
                [levels_object["PG"]]:{
                    [amount]:500
                },
                [levels_object["UG-DIPLOMA"]]:{
                    [amount]:300
                }
                
            },
            [courses_object['Dental']]:{
                [levels_object["UG"]]:{
                    [amount]:200
                },
                [levels_object["PG"]]:{
                    [amount]:500
                },
                [levels_object["UG-DIPLOMA"]]:{
                    [amount]:300
                }
            },
            [courses_object['Medical']]:{
                [levels_object["UG"]]:{
                    [amount]:200
                },
                [levels_object["PG"]]:{
                    [amount]:500
                },
                [levels_object["UG-DIPLOMA"]]:{
                    [amount]:300
                },
               
            }
        },
        [nationality_type_object['FOREIGN']]:{
            [courses_object['Ayurveda']]:{
                [levels_object["UG"]]:{
                    [amount]:400
                },
                [levels_object["PG"]]:{
                    [amount]:700
                },
                [levels_object["UG-DIPLOMA"]]:{
                    [amount]:400
                }
            },
            [courses_object['Dental']]:{
                [levels_object["UG"]]:{
                    [amount]:400
                },
                [levels_object["PG"]]:{
                    [amount]:700
                },
                [levels_object["UG-DIPLOMA"]]:{
                    [amount]:400
                }
            },
            [courses_object['Medical']]:{
                [levels_object["UG"]]:{
                    [amount]:400
                },
                [levels_object["PG"]]:{
                    [amount]:700
                },
                [levels_object["UG-DIPLOMA"]]:{
                    [amount]:400
                }
            }
        }
    }

}
module.exports={structure_of_fee};